// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BookMyShow.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookMyShow.Models;

public class User
{
    public int UserId { get; set; }

    [Required(ErrorMessage = "Please Enter the Username")]
    public string Username { get; set; }


    [RegularExpression(@"^(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", ErrorMessage = "Enter a valid password")]
    public string Pass { get; set; }

    public string FullName { get; set; }


    [Required(ErrorMessage = "Enter the Age")]
    [Range(1, 100, ErrorMessage = "Enter a valid age")]

    public int? Age { get; set; }

    [Required(ErrorMessage = "Please enter the Email")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Please select the Gender")]
    public string Gender { get; set; }

    [Required(ErrorMessage = "Please enter the Mobile no")]
    [RegularExpression(@"^\d{10}$", ErrorMessage = "Enter a valid mobile number")]

    public string MobileNo { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedAt { get; set; }

    public byte[] ProfilePic { get; set; }

    public string Security_Question { get; set; }

    public string Security_Answer { get; set; }

    [NotMapped]
    public string Captcha { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}
