// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideAggregatorAPI.Data;

#nullable disable

namespace RideAggregatorAPI.Migrations
{
    [DbContext(typeof(RideDbContext))]
    [Migration("20250625035739_dataa")]
    partial class dataa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideAggregatorAPI.Data.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverId");

                    b.HasIndex("UserId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Location", b =>
                {
                    b.Property<Guid>("LocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocId");

                    b.HasIndex("LocName")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.PickupRide", b =>
                {
                    b.Property<Guid>("PickupRideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLocation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceLocation")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PickupRideId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationLocation");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceLocation");

                    b.ToTable("PickupRides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.RentalRide", b =>
                {
                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HiredDays")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.ToTable("Rentalrides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Customer", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.User", "userdata")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userdata");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Driver", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.User", "userdata")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userdata");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.PickupRide", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.Customer", "Customerdata")
                        .WithMany("PickpRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.Location", "DestLocationdata")
                        .WithMany()
                        .HasForeignKey("DestinationLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.Driver", "Driverdata")
                        .WithMany("PickpRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.Location", "SrcLocationdata")
                        .WithMany()
                        .HasForeignKey("SourceLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customerdata");

                    b.Navigation("DestLocationdata");

                    b.Navigation("Driverdata");

                    b.Navigation("SrcLocationdata");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.RentalRide", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.Customer", "Customerdata")
                        .WithMany("RentalRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.Driver", "Driverdata")
                        .WithMany("RentalRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customerdata");

                    b.Navigation("Driverdata");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Customer", b =>
                {
                    b.Navigation("PickpRides");

                    b.Navigation("RentalRides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.Driver", b =>
                {
                    b.Navigation("PickpRides");

                    b.Navigation("RentalRides");
                });
#pragma warning restore 612, 618
        }
    }
}
