// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelEezzz1.Migrations
{
    [DbContext(typeof(TravelEezzEFContext))]
    partial class TravelEezzEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("seatCount")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1L,
                            LocationName = "HYD"
                        },
                        new
                        {
                            LocationId = 2L,
                            LocationName = "CHN"
                        },
                        new
                        {
                            LocationId = 3L,
                            LocationName = "Mumbai"
                        });
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceId"));

                    b.Property<long>("DestLocId")
                        .HasColumnType("bigint");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<long>("SerTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceLocId")
                        .HasColumnType("bigint");

                    b.HasKey("ServiceId");

                    b.HasIndex("DestLocId");

                    b.HasIndex("SerTypeId");

                    b.HasIndex("SourceLocId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ServiceType", b =>
                {
                    b.Property<long>("STypeId")
                        .HasColumnType("bigint");

                    b.Property<double>("PricePerKm")
                        .HasColumnType("float");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("STypeId");

                    b.HasIndex("ServiceTypeName")
                        .IsUnique();

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            STypeId = 1L,
                            PricePerKm = 12.5,
                            ServiceTypeName = "Express"
                        },
                        new
                        {
                            STypeId = 2L,
                            PricePerKm = 18.5,
                            ServiceTypeName = "Luxury"
                        });
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.HasOne("Service", "Travelservice")
                        .WithMany("CurBokings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Travelservice");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.HasOne("Location", "Destination")
                        .WithMany("DestServiceList")
                        .HasForeignKey("DestLocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServiceType", "ServiceType")
                        .WithMany("ServiceList")
                        .HasForeignKey("SerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Location", "Source")
                        .WithMany("SourceServiceList")
                        .HasForeignKey("SourceLocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("ServiceType");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("DestServiceList");

                    b.Navigation("SourceServiceList");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Navigation("CurBokings");
                });

            modelBuilder.Entity("ServiceType", b =>
                {
                    b.Navigation("ServiceList");
                });
#pragma warning restore 612, 618
        }
    }
}
