// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideAggrigationAPI.Data;

#nullable disable

namespace RideAggrigationAPI.Migrations
{
    [DbContext(typeof(RideAggrigateDbContext))]
    [Migration("20250625093937_migrations")]
    partial class migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideAggrigationAPI.Data.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerPhone")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Driver", b =>
                {
                    b.Property<Guid>("DiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DriverRating")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiverId");

                    b.HasIndex("UserId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.PicupDrop", b =>
                {
                    b.Property<Guid>("PickupDropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistinationLocationid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceLocationid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("numofdays")
                        .HasColumnType("int");

                    b.HasKey("PickupDropId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistinationLocationid");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceLocationid");

                    b.ToTable("PicupDrop");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Rental", b =>
                {
                    b.Property<Guid>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistinationLocationid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceLocationid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RentalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistinationLocationid");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceLocationid");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Customer", b =>
                {
                    b.HasOne("RideAggrigationAPI.Data.User", "userId")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userId");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Driver", b =>
                {
                    b.HasOne("RideAggrigationAPI.Data.User", "userId")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userId");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.PicupDrop", b =>
                {
                    b.HasOne("RideAggrigationAPI.Data.Customer", "customerid")
                        .WithMany("PicRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Location", "distlocid")
                        .WithMany()
                        .HasForeignKey("DistinationLocationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Driver", "driverid")
                        .WithMany("PicRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Location", "srclocid")
                        .WithMany()
                        .HasForeignKey("SourceLocationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customerid");

                    b.Navigation("distlocid");

                    b.Navigation("driverid");

                    b.Navigation("srclocid");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Rental", b =>
                {
                    b.HasOne("RideAggrigationAPI.Data.Customer", "customerid")
                        .WithMany("RentalRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Location", "distlocid")
                        .WithMany()
                        .HasForeignKey("DistinationLocationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Driver", "driverid")
                        .WithMany("RentalRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggrigationAPI.Data.Location", "srclocid")
                        .WithMany()
                        .HasForeignKey("SourceLocationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customerid");

                    b.Navigation("distlocid");

                    b.Navigation("driverid");

                    b.Navigation("srclocid");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Customer", b =>
                {
                    b.Navigation("PicRides");

                    b.Navigation("RentalRides");
                });

            modelBuilder.Entity("RideAggrigationAPI.Data.Driver", b =>
                {
                    b.Navigation("PicRides");

                    b.Navigation("RentalRides");
                });
#pragma warning restore 612, 618
        }
    }
}
