// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideAggregatorAPI.Data;

#nullable disable

namespace RideAggregatorAPI.Migrations
{
    [DbContext(typeof(RADBContext))]
    [Migration("20250624062614_prem")]
    partial class prem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideAggregatorAPI.Data.CustomerInfo", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("LoginId");

                    b.ToTable("CustomerInfos");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.DriverInfo", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverId");

                    b.HasIndex("LoginId");

                    b.ToTable("DriverInfos");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.LocationInfo", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("LocationInfos");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.PickUpDropRide", b =>
                {
                    b.Property<Guid>("PickupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PickupId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceId");

                    b.ToTable("pickUpDropRides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.RentalRides", b =>
                {
                    b.Property<Guid>("RetalRideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HiredDays")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RetalRideId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceId");

                    b.ToTable("RentalRides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.UserInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("URole")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.CustomerInfo", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.DriverInfo", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.PickUpDropRide", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.CustomerInfo", "Customer")
                        .WithMany("Rides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.LocationInfo", "DestLocation")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.DriverInfo", "Driver")
                        .WithMany("pickUpDropRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.LocationInfo", "SrcLocation")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DestLocation");

                    b.Navigation("Driver");

                    b.Navigation("SrcLocation");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.RentalRides", b =>
                {
                    b.HasOne("RideAggregatorAPI.Data.CustomerInfo", "Customer")
                        .WithMany("RentalRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.DriverInfo", "Driver")
                        .WithMany("RentalRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregatorAPI.Data.LocationInfo", "SrcLocation")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("SrcLocation");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.CustomerInfo", b =>
                {
                    b.Navigation("RentalRides");

                    b.Navigation("Rides");
                });

            modelBuilder.Entity("RideAggregatorAPI.Data.DriverInfo", b =>
                {
                    b.Navigation("RentalRides");

                    b.Navigation("pickUpDropRides");
                });
#pragma warning restore 612, 618
        }
    }
}
