// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideAggregateAPI.Data;

#nullable disable

namespace RideAggregateAPI.Migrations
{
    [DbContext(typeof(RADBContext))]
    [Migration("20250625102246_migrationride")]
    partial class migrationride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideAggregateAPI.DTO.CustomerInfo", b =>
                {
                    b.Property<Guid>("CustId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CustId");

                    b.HasIndex("LoginId");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.DriverInfo", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.HasIndex("LoginId");

                    b.ToTable("DriverInfo");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.Location", b =>
                {
                    b.Property<Guid>("LocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocId");

                    b.HasIndex("LocName")
                        .IsUnique();

                    b.ToTable("Location");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.UserInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("RideAggregateAPI.Data.PickUpDropRide", b =>
                {
                    b.Property<long>("pickUpId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CustomerCustId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("custId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("destinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("distance")
                        .HasColumnType("float");

                    b.Property<Guid>("driverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("sourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("pickUpId");

                    b.HasIndex("CustomerCustId");

                    b.HasIndex("destinationId");

                    b.HasIndex("driverId");

                    b.HasIndex("sourceId");

                    b.ToTable("PickUpDropRides");
                });

            modelBuilder.Entity("RideAggregateAPI.Data.RentalRide", b =>
                {
                    b.Property<Guid>("RetalRideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HiredDays")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RetalRideId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SourceId");

                    b.ToTable("RentalRide");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.CustomerInfo", b =>
                {
                    b.HasOne("RideAggregateAPI.DTO.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.DriverInfo", b =>
                {
                    b.HasOne("RideAggregateAPI.DTO.UserInfo", "userInfo")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userInfo");
                });

            modelBuilder.Entity("RideAggregateAPI.Data.PickUpDropRide", b =>
                {
                    b.HasOne("RideAggregateAPI.DTO.CustomerInfo", "Customer")
                        .WithMany("PickupDropRides")
                        .HasForeignKey("CustomerCustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregateAPI.DTO.Location", "DestLocation")
                        .WithMany()
                        .HasForeignKey("destinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregateAPI.DTO.DriverInfo", "Driver")
                        .WithMany("PickupRides")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregateAPI.DTO.Location", "SrcLocation")
                        .WithMany()
                        .HasForeignKey("sourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DestLocation");

                    b.Navigation("Driver");

                    b.Navigation("SrcLocation");
                });

            modelBuilder.Entity("RideAggregateAPI.Data.RentalRide", b =>
                {
                    b.HasOne("RideAggregateAPI.DTO.CustomerInfo", "Customer")
                        .WithMany("RentalRides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregateAPI.DTO.DriverInfo", "Driver")
                        .WithMany("RentalRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideAggregateAPI.DTO.Location", "SrcLocation")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("SrcLocation");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.CustomerInfo", b =>
                {
                    b.Navigation("PickupDropRides");

                    b.Navigation("RentalRides");
                });

            modelBuilder.Entity("RideAggregateAPI.DTO.DriverInfo", b =>
                {
                    b.Navigation("PickupRides");

                    b.Navigation("RentalRides");
                });
#pragma warning restore 612, 618
        }
    }
}
