// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideAppAgg;

#nullable disable

namespace RideAppAgg.Migrations
{
    [DbContext(typeof(RideAppDBContext))]
    partial class RideAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideAppAgg.Customer", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UId")
                        .HasColumnType("int");

                    b.HasKey("CId");

                    b.HasIndex("UId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RideAppAgg.Driver", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfRides")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UId")
                        .HasColumnType("int");

                    b.HasKey("DId");

                    b.HasIndex("UId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("RideAppAgg.Location", b =>
                {
                    b.Property<int>("LId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LId"));

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RideAppAgg.PickupDrop", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("DId")
                        .HasColumnType("int");

                    b.Property<int>("DropLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationLId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationLId1")
                        .HasColumnType("int");

                    b.Property<int>("PickupLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PId");

                    b.HasIndex("CId");

                    b.HasIndex("DId");

                    b.HasIndex("DropLocationId");

                    b.HasIndex("LocationLId");

                    b.HasIndex("LocationLId1");

                    b.HasIndex("PickupLocationId");

                    b.ToTable("PickupDrops");
                });

            modelBuilder.Entity("RideAppAgg.Ride", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<double>("CostPerKm")
                        .HasColumnType("float");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.HasKey("RId");

                    b.HasIndex("PId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("RideAppAgg.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RideAppAgg.Customer", b =>
                {
                    b.HasOne("RideAppAgg.User", "User")
                        .WithMany()
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RideAppAgg.Driver", b =>
                {
                    b.HasOne("RideAppAgg.User", "User")
                        .WithOne()
                        .HasForeignKey("RideAppAgg.Driver", "UId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RideAppAgg.PickupDrop", b =>
                {
                    b.HasOne("RideAppAgg.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideAppAgg.Driver", "Driver")
                        .WithMany("pickDs")
                        .HasForeignKey("DId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideAppAgg.Location", "DropLocation")
                        .WithMany()
                        .HasForeignKey("DropLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RideAppAgg.Location", null)
                        .WithMany("DropD")
                        .HasForeignKey("LocationLId");

                    b.HasOne("RideAppAgg.Location", null)
                        .WithMany("PickD")
                        .HasForeignKey("LocationLId1");

                    b.HasOne("RideAppAgg.Location", "PickupLocation")
                        .WithMany()
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("DropLocation");

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("RideAppAgg.Ride", b =>
                {
                    b.HasOne("RideAppAgg.PickupDrop", "PickupDrop")
                        .WithMany()
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupDrop");
                });

            modelBuilder.Entity("RideAppAgg.Driver", b =>
                {
                    b.Navigation("pickDs");
                });

            modelBuilder.Entity("RideAppAgg.Location", b =>
                {
                    b.Navigation("DropD");

                    b.Navigation("PickD");
                });
#pragma warning restore 612, 618
        }
    }
}
